# Generated by Django 5.0.4 on 2024-08-15 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nickname", models.CharField(max_length=30)),
                ("position", models.CharField(max_length=30)),
                ("subjects", models.CharField(max_length=30)),
                (
                    "image",
                    models.ImageField(default="default.png", upload_to="profile/"),
                ),
                ("bio", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
